//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDePrestamos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuotas
    {
        public int idcuota { get; set; }
        public int idprestamo { get; set; }
        public int numero_cuota { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public decimal monto_cuota { get; set; }
        public Nullable<decimal> monto_pagado { get; set; }
        public string estado { get; set; }
    
        public virtual Prestamos Prestamos { get; set; }
    }
}
