//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDePrestamos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public Prestamos()
        {
            this.Pagos = new HashSet<Pagos>();
            this.cuotas = new HashSet<cuotas>();
        }
    
        public int id_prestamo { get; set; }
        public int id_cliente { get; set; }
        public float monto { get; set; }
        public float interes { get; set; }
        public int plazo_meses { get; set; }
        public string Frecuencia_pagos { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual ICollection<cuotas> cuotas { get; set; }
    }
}
